//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAppServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class cities
    {
        public string name { get; set; }
        public int id { get; set; }
        public Nullable<double> location_lat { get; set; }
        public Nullable<double> location_lng { get; set; }
        public string country { get; set; }
        public string image_url { get; set; }
        public string description { get; set; }
    }
}
