//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAppServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class routes
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string sites { get; set; }
        public string image_url { get; set; }
        public Nullable<double> rate { get; set; }
        public string description { get; set; }
    }
}
