//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAppServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class sites
    {
        public string place_id { get; set; }
        public string name { get; set; }
        public string formatted_address { get; set; }
        public string formatted_phone_number { get; set; }
        public string international_phone_number { get; set; }
        public Nullable<double> rating { get; set; }
        public string google_id { get; set; }
        public Nullable<double> location_lat { get; set; }
        public Nullable<double> location_lng { get; set; }
        public string types { get; set; }
        public Nullable<long> id { get; set; }
        public string profile_photo { get; set; }
        public string album_photos { get; set; }
        public Nullable<int> city_id { get; set; }
        public string description { get; set; }
        public string seasons { get; set; }
        public string compositions { get; set; }
    }
}
