//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAppServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_paths
    {
        public int db_index { get; set; }
        public Nullable<long> user_id { get; set; }
        public Nullable<long> site_id1 { get; set; }
        public Nullable<long> site_id2 { get; set; }
        public Nullable<long> site_id3 { get; set; }
        public Nullable<long> site_id4 { get; set; }
        public Nullable<long> site_id5 { get; set; }
    }
}
